#!/bin/bash

#Start scripts
sed '/prep :/a\\ttouch prep' -i src/Makefile
[ $(getconf LONG_BIT) = 64 ] || patch -Np1 -i ../efivar-38-i686-1.patch
make ERRORS=
make install LIBDIR=/usr/lib

#End scripts
