#!/bin/bash

#Start scripts
./bootstrap                                &&
./configure --prefix=/usr --disable-static &&
make
./frontend/faac -o Front_Left.mp4 /usr/share/sounds/alsa/Front_Left.wav
faad Front_Left.mp4
aplay Front_Left.wav
make install

#End scripts
