#!/bin/bash

#Start scripts
mkdir bld &&
cd    bld &&

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DGIT_ARCHETYPE=1           \
      -Wno-dev ../source          &&
make
make install &&
rm -vf /usr/lib/libx265.a 

#End scripts
